// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_SjH2tDUbtPMu57ge1znVP_TyW6_i0g',
    appId: '1:340117004886:web:e954efe3fe1d3aa5e191f7',
    messagingSenderId: '340117004886',
    projectId: 'project-2-notifications',
    authDomain: 'project-2-notifications.firebaseapp.com',
    storageBucket: 'project-2-notifications.firebasestorage.app',
    measurementId: 'G-83H9B4DL6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACNPTvwUvGSAbsWMERuqtOslgcwGNNsH4',
    appId: '1:340117004886:android:2824d9f8e43f39b7e191f7',
    messagingSenderId: '340117004886',
    projectId: 'project-2-notifications',
    storageBucket: 'project-2-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZAKtDaSHCNbgrqnDv9jPqJuSdnhTYkFE',
    appId: '1:340117004886:ios:03a610d1fbcee6bae191f7',
    messagingSenderId: '340117004886',
    projectId: 'project-2-notifications',
    storageBucket: 'project-2-notifications.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZAKtDaSHCNbgrqnDv9jPqJuSdnhTYkFE',
    appId: '1:340117004886:ios:03a610d1fbcee6bae191f7',
    messagingSenderId: '340117004886',
    projectId: 'project-2-notifications',
    storageBucket: 'project-2-notifications.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF_SjH2tDUbtPMu57ge1znVP_TyW6_i0g',
    appId: '1:340117004886:web:59f323460191c742e191f7',
    messagingSenderId: '340117004886',
    projectId: 'project-2-notifications',
    authDomain: 'project-2-notifications.firebaseapp.com',
    storageBucket: 'project-2-notifications.firebasestorage.app',
    measurementId: 'G-ZEYBRSTKKE',
  );
}
