class CollectionPharmacyMockDataSource {
  Future<List<Map<String, dynamic>>> fetchPharmacies() async {
    await Future<void>.delayed(const Duration(milliseconds: 700));

    return <Map<String, dynamic>>[
      <String, dynamic>{
        'id': 'PH-001',
        'name': 'صيدلية النهضة',
        'area': 'المزة',
        'address': 'دمشق - المزة - شارع الجلاء',
        'phone_number': '0933123456',
        'official_balance': 12500,
        'account_status': 'has_debt',
        'has_pending_collection': false,
        'last_payment_amount': 2500,
        'last_payment_date': '2026-07-28T09:30:00.000Z',
      },
      <String, dynamic>{
        'id': 'PH-002',
        'name': 'صيدلية الشفاء',
        'area': 'جرمانا',
        'address': 'ريف دمشق - جرمانا - الساحة',
        'phone_number': '0944234567',
        'official_balance': 7800,
        'account_status': 'pending_collection',
        'has_pending_collection': true,
        'last_payment_amount': 1500,
        'last_payment_date': '2026-07-30T11:00:00.000Z',
      },
      <String, dynamic>{
        'id': 'PH-003',
        'name': 'صيدلية الحياة',
        'area': 'كفرسوسة',
        'address': 'دمشق - كفرسوسة - تنظيم كفرسوسة',
        'phone_number': '0955345678',
        'official_balance': 0,
        'account_status': 'settled',
        'has_pending_collection': false,
        'last_payment_amount': 4200,
        'last_payment_date': '2026-07-25T08:15:00.000Z',
      },
      <String, dynamic>{
        'id': 'PH-004',
        'name': 'صيدلية الأمل',
        'area': 'برزة',
        'address': 'دمشق - برزة - شارع الحافظ',
        'phone_number': '0966456789',
        'official_balance': 9300,
        'account_status': 'has_debt',
        'has_pending_collection': false,
        'last_payment_amount': 1000,
        'last_payment_date': '2026-07-20T10:45:00.000Z',
      },
      <String, dynamic>{
        'id': 'PH-005',
        'name': 'صيدلية ابن سينا',
        'area': 'الميدان',
        'address': 'دمشق - الميدان - شارع دق الباب',
        'phone_number': '0999567890',
        'official_balance': 4400,
        'account_status': 'pending_collection',
        'has_pending_collection': true,
        'last_payment_amount': 2200,
        'last_payment_date': '2026-07-31T13:20:00.000Z',
      },
      <String, dynamic>{
        'id': 'PH-006',
        'name': 'صيدلية النور',
        'area': 'باب توما',
        'address': 'دمشق - باب توما - شارع الآسية',
        'phone_number': '0988678901',
        'official_balance': 0,
        'account_status': 'settled',
        'has_pending_collection': false,
        'last_payment_amount': 3100,
        'last_payment_date': '2026-07-18T12:10:00.000Z',
      },
    ];
  }
}
